### ISSUE TITLE
[minor] The result counter does not update when filtering by folder

### ISSUE THREAD

**Issue by goofy-bz** [mozfr/transvision#525]
example of the above report:
* try https://transvision.mozfr.org/?recherche=top+sites&repo=aurora&sourcelocale=en-US&locale=fr&search_type=strings  
->  gives 9(en) + 3(fr) results
* now select folder "mobile"  
-> still displays 9 + 3 results though actual result is 2 + 0

**Comment by flodolo** [comment]
The number of results is generated server-side when you search, that's why it doesn't change when you filter (the filter actually hides the results belonging to other modules).

I agree that's a bit misleading, I will need to check how hard it's to determine the number and replace it with JavaScript.
