### ISSUE TITLE
Remove Gaia from Transvision

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#607]
Firefox OS is dead, we should remove Gaia from Transvision wich will simplify our code base.

**Comment by flodolo** [comment]
To be honest I don't agree: I think there's value in keeping gaia-l10n around, at least until we don't understand what's going to happen with Connected Devices (and TV in particular), and remove all older versions (branches) to make updates faster.

I get that removed code can always be restored, but it's not as easy as pressing a button to revert a commit, since the codebase moved ahead in the meantime.

**Comment by flodolo** [comment]
On other hand, if we drop support for all other versions of Gaia, it might make sense to drop the 'Gaia' view.

**Comment by pascalchevrel** [comment]
Let's do this in 2 steps, first we keep only gaia-l10n in Transvision and remove the Gaia view, and then when we get the final final confirmation that connected devices will not reuse the existing Gaia infrastructure to get l10n done (which I honestly don't believe they will do), then we remove the rest.

Note that from my POV, the longer we keep support in tools for Gaia and expose it as a project, the longer we will give false hopes to people that Firefox OS for phones is not a dead project. And I am not convinved that TVs are a good case (I also strongly think we shouldn't have the volunteer community work on the TV stuff as it will not benefit them but that's another subject ;))

**Comment by flodolo** [comment]
We might want to hold this until the whole TV thing is clear, and it won't happen before the hackathon :-\

I think it's safe to drop everything besides gaia-l10n and 2.5 at this point, and it can be done externally. I would wait a bit more before dropping all the code, Gaia view included.

**Comment by flodolo** [comment]
I'm going to close this, we can open a new one if/when we decide to remove gaia completely.
