### ISSUE TITLE
Status Overview does not update

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#662]
I guess https://transvision.mozfr.org/stats/?repo=aurora hasn't been updated for a while, listing 114 missing string for Czech (cs) and 823 for Slovak (sk), but both of them are complete in Aurora (see https://l10n.mozilla.org/shipping/dashboard?locale=cs and https://l10n.mozilla.org/shipping/dashboard?locale=sk).

**Comment by flodolo** [comment]
I believe there are some issues with the code, I don't remember this view using stored data.

It might even make sense to remove it completely since we have
https://transvision.mozfr.org/showrepos/?locale=cs

And rename "Health Status Check" as "Locale statistics" and move it to the right column (the central one starts to be pretty crowded).
