### ISSUE TITLE
Add link directly to Pontoon

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#790]
Pontoon has introduced direct links to entities. It would be nice to get to Pontoon by one click from the Transvision results.

**Comment by flodolo** [comment]
Some thoughts:
* As far as I can tell we can't link to a specific string, because we don't know the numeric ID of the string. I think the best we could do is to link to the file.
* We would need to map strings to Pontoon products to make it work.
* Not all locales work on Pontoon.
* Not all products are available on Pontoon (e.g. central or release).
* We already have a ton of links around strings.

The logic to make that link would be huge, and I think not many locales would benefit from it.

**Comment by TheoChevalier** [comment]
Done in https://github.com/mozfr/transvision/commit/6876a6d910f94b7f645ef3346aa3911ea2e37771
