### ISSUE TITLE
@@missing@@ in bug reports

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#827]
Just noticed we’re sending @@missing@@ to Bugzilla when filing a bug from a missing string, we should probably display something else.

Can be tested on https://transvision.mozfr.org/?sourcelocale=en-US&locale=fr&repo=aurora&search_type=entities&recherche=mail/chrome/messenger/addressbook/abContactsPanel.dtd:mailingListPropertiesMenu.label&perfect_match=perfect_match

**Comment by rajivjhaimin** [comment]
@TheoChevalier  I would like to work on the issue.

**Comment by flodolo** [comment]
Hi, feel free to start and ask questions if you have any.

**Comment by flodolo** [comment]
Updated link: https://transvision.mozfr.org/?recherche=firstrun_urlbar_message2&repo=gecko_strings&sourcelocale=en-US&locale=de&search_type=entities

**Comment by ayushpratap** [comment]
I would like to take it up , can someone tell me how to reproduce the bug and what should be the expected output?

**Comment by flodolo** [comment]
> how to reproduce the bug and what should be the expected output

Open https://transvision.mozfr.org/?recherche=securitySiteDataCookiesOnly&repo=gecko_strings&sourcelocale=en-US&locale=de&search_type=entities and click on <report a bug>

The open bug report shouldn't have `@@ missing @@`

```
The string:
Yes, cookies

Is translated as:
@@missing@@
```

Either write `(missing translation)` or drop that paragraph, the former would be much easier.

**Comment by flodolo** [comment]
> I checked the above-mentioned link and

I'm not following. Did you click the link to report a bug, under "Warning: Missing string"?

**Comment by ayushpratap** [comment]
@flodolo I wanted to work on this bug. So I asked how to reproduce it.
Then you gave the following link
[THE LINK]( https://transvision.mozfr.org/?recherche=securitySiteDataCookiesOnly&repo=gecko_strings&sourcelocale=en-US&locale=de&search_type=entities)

Whereas per you, the string " Yes, cookies " should be " @@missing@@" but instead in place of "@@missing@@" it is "Warning: Missing string"

**Comment by flodolo** [comment]
This is the initial comment

> Just noticed we’re sending @@missing@@ to Bugzilla when filing a bug from a missing string, we should probably display something else.

As expained:
1. Click on [the link](https://transvision.mozfr.org/?recherche=securitySiteDataCookiesOnly&repo=gecko_strings&sourcelocale=en-US&locale=de&search_type=entities), then click on *<report a bug>* displayed under `Warning: Missing string`
2. Check what the Bugzilla draft says.

```
Is translated as:
@@missing@@
```

It shouldn't be `@@missing@@`, it should be something else (comment 9).

**Comment by ayushpratap** [comment]
Okay, I got it. So the actual string which is saved to Bugzilla is @@missing@@ instead of "Missing string".
I will have a look at it.

**Comment by flodolo** [comment]
This is happening because missing strings are internally stored as `@@missing@@`, but that value should be changed when creating the link to Bugzilla.

**Comment by ayushpratap** [comment]
Okay, so what we can do is, we can check for a 'missing string' and explicitly add a 'warning string'. Hence instead of "@@missing@@", "Warning string" will be stored.

**Comment by flodolo** [comment]
No, you should fix the code generating the link to account for that `@@missing@@`, and replace it with something readable ;-)

That's only a few lines fix, your approach (change the value stored internally) would require a complete rewrite of several parts, back-end and front-end.

**Comment by ayushpratap** [comment]
Well, I will do that, can you suggest me the directory/files I should look for the possible fix.
And any advice on how to navigate the code with ease.

**Comment by flodolo** [comment]
There is a Bugzilla class
https://github.com/mozfr/transvision/blob/master/app/classes/Transvision/Bugzilla.php

**Comment by enderandpeter** [comment]
A modern-day example can be seen here: https://transvision.mozfr.org/3locales/?recherche=%C2%A1Hola%2C+Mundo!&repo=all_projects&sourcelocale=es-ES&locale=es-AR&locale2=es-CL&search_type=strings where es-CL is missing the string.

Yes, I do think https://github.com/mozfr/transvision/blob/main/app/classes/Transvision/Bugzilla.php#L61 is about the area to address. So, instead of producing

```
The string:
¡Hola, Mundo!

Is translated as:
@@missing@@

And should be:

```

I was hoping to establish what would be better. Are you thinking that `@@missing@@` should simply be removed from the Bugzilla comment? Or when `$target_string` is `@@missing@@` should the whole comment be rephrased, perhaps along the lines of:

```
Translation is missing for the string "¡Hola, Mundo!"
```

because it may not be clear what the translation es-CL translation should be?

**Comment by flodolo** [comment]
> I was hoping to establish what would be better. Are you thinking that `@@missing@@` should simply be removed from the Bugzilla comment? Or when `$target_string` is `@@missing@@` should the whole comment be rephrased, perhaps along the lines of:

We have very complex multiline strings ([example](https://transvision.mozfr.org/?sourcelocale=en-US&locale=af&repo=gecko_strings&search_type=entities&recherche=browser/chrome/overrides/netError.dtd:proxyResolveFailure.longDesc&entire_string=entire_string)), so putting the source text inside a sentence won't scale.

Note that the typical use case would be to search for an English string, then report the bug from there. [Here's an example](https://transvision.mozfr.org/?sourcelocale=en-US&locale=af&repo=all_projects&search_type=entities&recherche=browser/browser/aboutPocket.ftl:pocket-panel-home-welcome-back&entire_string=entire_string).

One nice option would be to change the template for this specific case, e.g. in the string above, instead of

```
The string:
Welcome Back

Is translated as:
@@missing@@

And should be:
```


```
Source string:
Welcome Back

This string has not been translated yet. Proposed translation:
```
