### ISSUE TITLE
Add the handy links to the pages in the QA View

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozfr/transvision#870]
When I use Access Keys and Translation Consistency views really miss the direct link to translation tool but suppose others can benefit from having them in the other views too.

**Comment by TheoChevalier** [comment]
Thank you for filing the issue, @StoyanDimitrov :) Definitely agree that it would be a great addition, but I think we should wait for x-channel first because it will make it easier to implement.
Should be trivial for the accesskeys view, maybe not so much for the consistency one (the page is already heavy)
